name: Carbon Credit Verification CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: carbon_credits_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    - name: Run backend tests
      run: |
        python test_backend.py
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/carbon_credits_test

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        cd frontend
        npm install
    - name: Run frontend tests
      run: |
        cd frontend
        npm test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest-asyncio playwright pytest-playwright pytest-xdist
    
    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm install
    
    - name: Install Playwright browsers
      run: |
        playwright install chromium firefox webkit
        playwright install-deps
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Run E2E Tests - Authentication Flow
      run: |
        cd tests/e2e
        chmod +x run_tests.sh
        ./run_tests.sh --auth --parallel
      env:
        CI: true
        HEADLESS: true
    
    - name: Run E2E Tests - Authentication Failures
      run: |
        cd tests/e2e
        ./run_tests.sh --auth-failures --parallel
      env:
        CI: true
        HEADLESS: true
    
    - name: Run E2E Tests - Dashboard
      run: |
        cd tests/e2e
        ./run_tests.sh --dashboard --parallel
      env:
        CI: true
        HEADLESS: true
    
    - name: Run E2E Tests - Complete Suite
      run: |
        cd tests/e2e
        pytest --maxfail=5 --tb=short --html=report.html --self-contained-html
      env:
        CI: true
        HEADLESS: true
    
    - name: Upload E2E Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-test-results
        path: |
          tests/e2e/report.html
          tests/e2e/test-results/
          tests/e2e/screenshots/
          tests/e2e/videos/
    
    - name: Upload E2E Test Screenshots on Failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: e2e-failure-screenshots
        path: tests/e2e/screenshots/

  validate-implementation:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, e2e-tests]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    - name: Validate implementation
      run: |
        python validate_implementation.py 